ifneq ($(TARGET_SIMULATOR),true)

LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_PRELINK_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := hdmi
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_C_INCLUDES := kernel

LOCAL_SRC_FILES:= hdmi.c

LOCAL_STATIC_LIBRARIES := 
include $(BUILD_EXECUTABLE)

endif  # TARGET_SIMULATOR != true
