#define	BASE_CMU_ADDR	 0x5300000 


#define	PLL1CONTROL 	BASE_CMU_ADDR + 0x00
#define	PLL2CONTROL  	BASE_CMU_ADDR + 0x04
#define	PLL3CONTROL  	BASE_CMU_ADDR + 0x08
#define	PLL4CONTROL  	BASE_CMU_ADDR + 0x0c
#define	WIFIPLLCONTROL  BASE_CMU_ADDR + 0x10
#define	CPUCLKCNTRL  	BASE_CMU_ADDR + 0x14
#define	COMCLKSEL  		BASE_CMU_ADDR + 0x18
#define	CLKSWCNTRL  	BASE_CMU_ADDR + 0x1c
#define	CLKDIVCNTRL1  	BASE_CMU_ADDR + 0x20
#define	CLKDIVCNTRL2  	BASE_CMU_ADDR + 0x24
#define	CLKDIVCNTRL3  	BASE_CMU_ADDR + 0x28
#define	CLKDIVCNTRL4  	BASE_CMU_ADDR + 0x2c
#define	CLKDIVCNTRL5  	BASE_CMU_ADDR + 0x30
#define	CLKDIVCNTRL6  	BASE_CMU_ADDR + 0x34
#define	LPTMRR  		BASE_CMU_ADDR + 0x38
#define	CLKOSCCR  		BASE_CMU_ADDR + 0x3c
#define	SWSYSRST  		BASE_CMU_ADDR + 0x40
#define	SWWRMRST  		BASE_CMU_ADDR + 0x44
#define	RSTSR  			BASE_CMU_ADDR + 0x48
#define	WRPR  			BASE_CMU_ADDR + 0x4c
#define	SWCHWRST1  		BASE_CMU_ADDR + 0x50
#define	SWCHWRST2  		BASE_CMU_ADDR + 0x54
#define	SWCLKENR1  		BASE_CMU_ADDR + 0x58
#define	SWCLKENR2  		BASE_CMU_ADDR + 0x5c
#define	CUSTATR  		BASE_CMU_ADDR + 0x60
#define	SWOVRCTL  		BASE_CMU_ADDR + 0x64
#define	CMU_TEST  		BASE_CMU_ADDR + 0x68
